//  Any lighten and darken variants not provided will still be generated by vuetify
// Please check https://vuetifyjs.com/en/customization/theme for more info

/* eslint-disable */
import colors from './colors';

export default {
  primary: colors.primary,
  secondary: colors.secondary,
  grey: colors.grey,
  status_error: colors.status.error,
  status_success: colors.status.success,
  status_warning: colors.status.warning,
  notification_error: colors.notifications.red,
  notification_success: colors.notifications.green,
  notification_warning: colors.notifications.yellow,
  notification_info: colors.notifications.blue,
  black: colors.black,
  white: colors.white,
};
